import { type AppConfig } from "~/config";
import type { InstallPayload } from "~/types/install";

export function buildConfigTs(payload: InstallPayload): string {
  const timestamp = new Date().toISOString();

  return `// Generated by MailForge installer — ${timestamp}

import "server-only";

export interface AppSection {
  name: string;
  tagline: string;
  logo: string;
  favicon: string;
  url: string;
}

export interface ThemeSection {
  defaultMode: "light" | "dark" | "system";
  primaryColor: string;
  accentColor: string;
  fontFamily: string;
  borderRadius: "none" | "sm" | "md" | "lg" | "xl";
  density: "compact" | "comfortable" | "spacious";
  sidebarPosition: "left" | "right";
  mailListLayout: "default" | "preview" | "minimal" | "cards";
  animationsEnabled: boolean;
}

export interface ImapConfig {
  host: string;
  port: number;
  tls: boolean;
}

export interface SmtpConfig {
  host: string;
  port: number;
  secure: boolean;
}

export interface MailSection {
  imap: ImapConfig;
  smtp: SmtpConfig;
  syncIntervalSeconds: number;
  maxAttachmentSizeMB: number;
  defaultFromName: string;
  allowedDomains: string[];
  maxAccountsPerUser: number;
}

export interface FeaturesSection {
  compose: boolean;
  richText: boolean;
  attachments: boolean;
  contacts: boolean;
  labels: boolean;
  filters: boolean;
  snooze: boolean;
  scheduleSend: boolean;
  unsubscribeDetection: boolean;
  readReceipts: boolean;
  aiAssist: boolean;
  multiAccount: boolean;
  delegation: boolean;
  importExport: boolean;
  encryptionPGP: boolean;
}

export interface BehaviorSection {
  markReadDelaySeconds: number | null;
  defaultReplyAll: boolean;
  sendUndoWindowSeconds: number;
  threadView: boolean;
  pagination: "paged" | "infinite";
  defaultSort: "date" | "sender" | "subject";
  autoSaveDraftSeconds: number;
  confirmBeforeDelete: boolean;
}

export interface AuthProvidersSection {
  google: boolean;
  github: boolean;
  microsoft: boolean;
  magicLink: boolean;
  credentials: boolean;
}

export interface TwoFactorSection {
  enabled: boolean;
  required: boolean;
}

export interface AuthSection {
  allowRegistration: boolean;
  allowedEmailDomains: string[] | null;
  requireEmailVerification: boolean;
  sessionMaxAgeSeconds: number;
  providers: AuthProvidersSection;
  twoFactor: TwoFactorSection;
}

export interface StorageSection {
  provider: "s3" | "r2" | "local";
  bucket: string;
  region: string;
  publicUrl: string;
}

export interface NotificationsSection {
  browser: boolean;
  sound: boolean;
  soundFile: string;
  emailDigest: boolean;
  digestIntervalHours: number;
}

export interface AdvancedSection {
  rateLimitPerMinute: number;
  maxConcurrentImap: number;
  searchProvider: "database" | "meilisearch";
  logLevel: "error" | "warn" | "info" | "debug";
  maintenanceMode: boolean;
}

export interface RateLimitEndpoint {
  windowMs: number;
  max: number;
}

export interface BruteForceSection {
  maxAttempts: number;
  lockoutDurationSeconds: number;
  backoffMultiplier: number;
}

export interface SecuritySection {
  rateLimit: {
    global: RateLimitEndpoint;
    login: RateLimitEndpoint;
    sendEmail: RateLimitEndpoint;
    syncTrigger: RateLimitEndpoint;
    search: RateLimitEndpoint;
    imapConnectionsPerUser: number;
    smtpSendsPerMinute: number;
  };
  bruteForce: BruteForceSection;
}

export interface AppConfig {
  app: AppSection;
  theme: ThemeSection;
  mail: MailSection;
  features: FeaturesSection;
  behavior: BehaviorSection;
  auth: AuthSection;
  storage: StorageSection;
  notifications: NotificationsSection;
  advanced: AdvancedSection;
  security: SecuritySection;
}

export const config: AppConfig = {
  app: {
    name: "${payload.app.name}",
    tagline: "${payload.app.tagline ?? ""}",
    logo: "${payload.app.logo ?? "/logo.svg"}",
    favicon: "/favicon.ico",
    url: "${payload.app.url}",
  },

  theme: {
    defaultMode: "${payload.app.theme.defaultMode}",
    primaryColor: "${payload.app.theme.primaryColor}",
    accentColor: "${payload.app.theme.primaryColor}",
    fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    borderRadius: "md",
    density: "${payload.app.theme.density}",
    sidebarPosition: "${payload.app.theme.sidebarPosition}",
    mailListLayout: "${payload.app.theme.mailListLayout}",
    animationsEnabled: ${payload.app.theme.animationsEnabled},
  },

  mail: {
    imap: {
      host: "${payload.mail.imap.host}",
      port: ${payload.mail.imap.port},
      tls: ${payload.mail.imap.tls},
    },
    smtp: {
      host: "${payload.mail.smtp.host}",
      port: ${payload.mail.smtp.port},
      secure: ${payload.mail.smtp.secure},
    },
    syncIntervalSeconds: ${payload.mail.syncInterval},
    maxAttachmentSizeMB: ${payload.mail.maxAttachmentSize},
    defaultFromName: "${payload.admin.name}",
    allowedDomains: ${JSON.stringify(payload.mail.allowedDomains)},
    maxAccountsPerUser: 5,
  },

  features: {
    compose: true,
    richText: true,
    attachments: true,
    contacts: true,
    labels: true,
    filters: true,
    snooze: true,
    scheduleSend: true,
    unsubscribeDetection: true,
    readReceipts: false,
    aiAssist: false,
    multiAccount: true,
    delegation: false,
    importExport: true,
    encryptionPGP: false,
  },

  behavior: {
    markReadDelaySeconds: 2,
    defaultReplyAll: false,
    sendUndoWindowSeconds: 10,
    threadView: true,
    pagination: "infinite",
    defaultSort: "date",
    autoSaveDraftSeconds: 30,
    confirmBeforeDelete: true,
  },

  auth: {
    allowRegistration: ${payload.auth.allowRegistration},
    allowedEmailDomains: ${payload.auth.allowedDomains.length > 0 ? JSON.stringify(payload.auth.allowedDomains) : "null"},
    requireEmailVerification: ${payload.auth.requireEmailVerification},
    sessionMaxAgeSeconds: ${payload.auth.sessionDays * 24 * 60 * 60},
    providers: {
      google: ${payload.auth.providers.google},
      github: ${payload.auth.providers.github},
      microsoft: ${payload.auth.providers.microsoft},
      magicLink: ${payload.auth.providers.magicLink},
      credentials: ${payload.auth.providers.credentials},
    },
    twoFactor: {
      enabled: ${payload.auth.enable2FA},
      required: ${payload.auth.require2FA},
    },
  },

  storage: {
    provider: "local",
    bucket: "mailforge-attachments",
    region: "auto",
    publicUrl: "/uploads",
  },

  notifications: {
    browser: true,
    sound: true,
    soundFile: "/sounds/notification.mp3",
    emailDigest: false,
    digestIntervalHours: 24,
  },

  advanced: {
    rateLimitPerMinute: 60,
    maxConcurrentImap: 5,
    searchProvider: "database",
    logLevel: "info",
    maintenanceMode: false,
  },

  security: {
    rateLimit: {
      global: { windowMs: 60_000, max: 200 },
      login: { windowMs: 900_000, max: 10 },
      sendEmail: { windowMs: 60_000, max: 20 },
      syncTrigger: { windowMs: 60_000, max: 5 },
      search: { windowMs: 60_000, max: 30 },
      imapConnectionsPerUser: 3,
      smtpSendsPerMinute: 10,
    },
    bruteForce: {
      maxAttempts: 5,
      lockoutDurationSeconds: 900,
      backoffMultiplier: 2,
    },
  },
};
`;
}

export async function writeConfigTs(
  payload: InstallPayload
): Promise<void> {
  const fs = await import("fs/promises");
  const path = await import("path");

  const content = buildConfigTs(payload);
  await fs.writeFile(
    path.join(process.cwd(), "config.ts"),
    content,
    "utf-8"
  );
}